services:
  python-app:
    image: rishabhraj7/python-app
    build: .
    ports:
      - "5000:5000"
    container_name: flask-docker-app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: